In [1]:
!nvidia-smi

Thu May 30 05:54:35 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
!git clone https://github.com/Franck-Dernoncourt/pubmed-rct.git


Cloning into 'pubmed-rct'...
remote: Enumerating objects: 39, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 39 (delta 8), reused 5 (delta 5), pack-reused 25
Receiving objects: 100% (39/39), 177.08 MiB | 21.39 MiB/s, done.
Resolving deltas: 100% (15/15), done.


In [3]:
#directory
data_dir = "pubmed-rct/PubMed_20k_RCT_numbers_replaced_with_at_sign/"

In [4]:
# Check all of the filenames in the target directory
import os
filenames = [data_dir + filename for filename in os.listdir(data_dir)]
filenames

['pubmed-rct/PubMed_20k_RCT_numbers_replaced_with_at_sign/dev.txt',
 'pubmed-rct/PubMed_20k_RCT_numbers_replaced_with_at_sign/train.txt',
 'pubmed-rct/PubMed_20k_RCT_numbers_replaced_with_at_sign/test.txt']

#preprocessing the  data

In [5]:
def get_lines(filename):
  """
  Reads filename (a text file) and returns the lines of text as a list.

  Args:
      filename: a string containing the target filepath to read.

  Returns:
      A list of strings with one string per line from the target filename.
      For example:
      ["this is the first line of filename",
       "this is the second line of filename",
       "..."]
  """
  with open(filename, "r") as f:
    return f.readlines()

In [6]:
train_lines = get_lines(data_dir + "train.txt")
train_lines[:20]

['###24293578\n',
 'OBJECTIVE\tTo investigate the efficacy of @ weeks of daily low-dose oral prednisolone in improving pain , mobility , and systemic low-grade inflammation in the short term and whether the effect would be sustained at @ weeks in older adults with moderate to severe knee osteoarthritis ( OA ) .\n',
 'METHODS\tA total of @ patients with primary knee OA were randomized @:@ ; @ received @ mg/day of prednisolone and @ received placebo for @ weeks .\n',
 'METHODS\tOutcome measures included pain reduction and improvement in function scores and systemic inflammation markers .\n',
 'METHODS\tPain was assessed using the visual analog pain scale ( @-@ mm ) .\n',
 'METHODS\tSecondary outcome measures included the Western Ontario and McMaster Universities Osteoarthritis Index scores , patient global assessment ( PGA ) of the severity of knee OA , and @-min walk distance ( @MWD ) .\n',
 'METHODS\tSerum levels of interleukin @ ( IL-@ ) , IL-@ , tumor necrosis factor ( TNF ) - , and 

## get the lines on the test data

In [7]:
test_lines = get_lines(data_dir + "test.txt")
test_lines[:20]

['###24845963\n',
 'BACKGROUND\tThis study analyzed liver function abnormalities in heart failure patients admitted with severe acute decompensated heart failure ( ADHF ) .\n',
 'RESULTS\tA post hoc analysis was conducted with the use of data from the Evaluation Study of Congestive Heart Failure and Pulmonary Artery Catheterization Effectiveness ( ESCAPE ) .\n',
 'RESULTS\tLiver function tests ( LFTs ) were measured at @ time points from baseline , at discharge , and up to @ months follow-up .\n',
 'RESULTS\tSurvival analyses were used to assess the association between admission Model of End-Stage Liver Disease Excluding International Normalized Ratio ( MELD-XI ) scores and patient outcome.There was a high prevalence of abnormal baseline ( admission ) LFTs ( albumin @ % , aspartate transaminase @ % , alanine transaminase @ % , and total bilirubin @ % ) .\n',
 "RESULTS\tThe percentage of patients with abnormal LFTs decreased significantly from baseline to @-months ' follow-up .\n",
 'RE

Arrange the data in this format
```
[
  {'line_number': 0,
  'target': 'OBJECTIVE',
  'text': 'to investigate the efficacy of @ weeks of daily low-dose oral prednisolone in improving pain , mobility , and systemic low-grade inflammation in the short term and whether the effect would be sustained at @ weeks in older adults with moderate to severe knee osteoarthritis ( oa ) .',
  'total_lines': 11},
  ...]
```

In [8]:
def preprocess_text_with_line_numbers(input_lines):
  abstract_lines = ""
  abstract_samples = []


  for line in input_lines:
    if line.startswith("###"):
      abstract_id = line
      abstract_lines = ""
    elif line.isspace():
      abstract_line_split = abstract_lines.splitlines()


      for abstract_line_number, abstract_line in enumerate(abstract_line_split):
        line_data = {}
        target_text_split = abstract_line.split("\t")
        line_data["target"] = target_text_split[0]
        line_data["text"] = target_text_split[1].lower()
        line_data["line_number"] = abstract_line_number
        line_data["total_lines"] = len(abstract_line_split) - 1
        abstract_samples.append(line_data)

    else:
      abstract_lines += line

  return abstract_samples

In [9]:
validate_lines = get_lines(data_dir + "dev.txt" )
train_sample = preprocess_text_with_line_numbers(train_lines)
test_sample = preprocess_text_with_line_numbers(test_lines)
validation_sample = preprocess_text_with_line_numbers(validate_lines)
train_sample[:10]


[{'target': 'OBJECTIVE',
  'text': 'to investigate the efficacy of @ weeks of daily low-dose oral prednisolone in improving pain , mobility , and systemic low-grade inflammation in the short term and whether the effect would be sustained at @ weeks in older adults with moderate to severe knee osteoarthritis ( oa ) .',
  'line_number': 0,
  'total_lines': 11},
 {'target': 'METHODS',
  'text': 'a total of @ patients with primary knee oa were randomized @:@ ; @ received @ mg/day of prednisolone and @ received placebo for @ weeks .',
  'line_number': 1,
  'total_lines': 11},
 {'target': 'METHODS',
  'text': 'outcome measures included pain reduction and improvement in function scores and systemic inflammation markers .',
  'line_number': 2,
  'total_lines': 11},
 {'target': 'METHODS',
  'text': 'pain was assessed using the visual analog pain scale ( @-@ mm ) .',
  'line_number': 3,
  'total_lines': 11},
 {'target': 'METHODS',
  'text': 'secondary outcome measures included the western ontari

## Change the data to dataframe for a better visualization

In [10]:
import pandas as pd

train_df = pd.DataFrame(train_sample)
test_df = pd.DataFrame(test_sample)
validate_df = pd.DataFrame(validation_sample)
train_df.head(15)

target                                               text  \
0     OBJECTIVE  to investigate the efficacy of @ weeks of dail...   
1       METHODS  a total of @ patients with primary knee oa wer...   
2       METHODS  outcome measures included pain reduction and i...   
3       METHODS  pain was assessed using the visual analog pain...   
4       METHODS  secondary outcome measures included the wester...   
5       METHODS  serum levels of interleukin @ ( il-@ ) , il-@ ...   
6       RESULTS  there was a clinically relevant reduction in t...   
7       RESULTS  the mean difference between treatment arms ( @...   
8       RESULTS  further , there was a clinically relevant redu...   
9       RESULTS  these differences remained significant at @ we...   
10      RESULTS  the outcome measures in rheumatology clinical ...   
11  CONCLUSIONS  low-dose oral prednisolone had both a short-te...   
12   BACKGROUND  emotional eating is associated with overeating...   
13   BACKGROUND  yet , empirical evidence for individual ( trai...   
14    OBJECTIVE  the aim of this study was to test if attention...   

    line_number  total_lines  
0             0           11  
1             1           11  
2             2           11  
3             3           11  
4             4           11  
5             5           11  
6             6           11  
7             7           11  
8             8           11  
9             9           11  
10           10           11  
11           11           11  
12            0           10  
13            1           10  
14            2           10

In [11]:
train_sentences = train_df["text"].tolist()
val_sentences = validate_df["text"].tolist()
test_sentences = test_df["text"].tolist()

## Make numeric labels (ML models require numeric labels)


In [12]:
# One hot encode labels
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder = OneHotEncoder(sparse_output=False)
train_labels_one_hot = one_hot_encoder.fit_transform(train_df["target"].to_numpy().reshape(-1, 1))
val_labels_one_hot = one_hot_encoder.transform(validate_df["target"].to_numpy().reshape(-1, 1))
test_labels_one_hot = one_hot_encoder.transform(test_df["target"].to_numpy().reshape(-1, 1))

# Check what training labels look like
train_labels_one_hot

array([[0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       ...,
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

### Label encode labels

In [13]:
# Extract labels ("target" columns) and encode them into integers
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
train_labels_encoded = label_encoder.fit_transform(train_df["target"].to_numpy())
val_labels_encoded = label_encoder.transform(validate_df["target"].to_numpy())
test_labels_encoded = label_encoder.transform(test_df["target"].to_numpy())

# Check what training labels look like
train_labels_encoded

array([3, 2, 2, ..., 4, 1, 1])

In [14]:
# Get class names from LabelEncoder instance
num_classes = len(label_encoder.classes_)
class_names = label_encoder.classes_
class_names

array(['BACKGROUND', 'CONCLUSIONS', 'METHODS', 'OBJECTIVE', 'RESULTS'],
      dtype=object)

# Model 1 Naive Bayes Classifier

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

# Create a pipeline
model_0 = Pipeline([
  ("tf-idf", TfidfVectorizer()),
  ("clf", MultinomialNB())
])

# Fit the pipeline to the training data
model_0.fit(X=train_sentences,
            y=train_labels_encoded);

In [16]:
# Evaluate baseline on validation dataset
model_0.score(X=val_sentences,
              y=val_labels_encoded)

0.7218323844829869

In [17]:
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
def calculate_results(y_true, y_pred):

  # Calculate model accuracy
  model_accuracy = accuracy_score(y_true, y_pred) * 100
  # Calculate model precision, recall and f1 score using "weighted average
  model_precision, model_recall, model_f1, _ = precision_recall_fscore_support(y_true, y_pred, average="weighted")
  model_results = {"accuracy": model_accuracy,
                  "precision": model_precision,
                  "recall": model_recall,
                  "f1": model_f1}
  return model_results

In [18]:
validate_pred = model_0.predict(val_sentences)
calculate_results(val_labels_encoded , validate_pred)

{'accuracy': 72.1832384482987,
 'precision': 0.7186466952323352,
 'recall': 0.7218323844829869,
 'f1': 0.6989250353450294}

## Preparing our data for deep sequence models


In [19]:
import tensorflow as tf
import numpy as np
from tensorflow.keras import layers

In [20]:
max_tokens = 68000
# Create text vectorizer

from tensorflow.keras.layers import TextVectorization

text_vectorizer = TextVectorization(max_tokens=max_tokens,
                                    output_sequence_length=55)

text_vectorizer.adapt(train_sentences)


In [21]:
# Test out text vectorizer
import random
target_sentence = random.choice(train_sentences)
print(f"Text:\n{target_sentence}")
print(f"\nLength of text: {len(target_sentence.split())}")
print(f"\nVectorized text:\n{text_vectorizer([target_sentence])}")

Text:
the total of @ carotid atherosclerosis patients were randomly divided into the intervention group ( @ cases , treated with shoushen granule ) and the control group ( @ cases , treated with pravastatin ) .

Length of text: 36

Vectorized text:
[[    2    76     4  1839  2813    12     9    92   471   143     2    38
     13   263   172     7 28546  5285     3     2    35    13   263   172
      7  8004     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0]]


In [22]:
# How many words in our training vocabulary?
rct_20k_text_vocab = text_vectorizer.get_vocabulary()

In [23]:
# Create token embedding layer
token_embed = layers.Embedding(input_dim=len(rct_20k_text_vocab), # length of vocabulary
                               output_dim=128,
                               mask_zero=True,
                               name="token_embedding")

In [24]:
# Turn our data into TensorFlow Datasets
train_dataset = tf.data.Dataset.from_tensor_slices((train_sentences, train_labels_one_hot))
valid_dataset = tf.data.Dataset.from_tensor_slices((val_sentences, val_labels_one_hot))
test_dataset = tf.data.Dataset.from_tensor_slices((test_sentences, test_labels_one_hot))

train_dataset

<_TensorSliceDataset element_spec=(TensorSpec(shape=(), dtype=tf.string, name=None), TensorSpec(shape=(5,), dtype=tf.float64, name=None))>

In [25]:
# Take the TensorSliceDataset's and turn them into prefetched batches
train_dataset = train_dataset.batch(32).prefetch(tf.data.AUTOTUNE)
valid_dataset = valid_dataset.batch(32).prefetch(tf.data.AUTOTUNE)
test_dataset = test_dataset.batch(32).prefetch(tf.data.AUTOTUNE)

train_dataset

<_PrefetchDataset element_spec=(TensorSpec(shape=(None,), dtype=tf.string, name=None), TensorSpec(shape=(None, 5), dtype=tf.float64, name=None))>

## Model 2 Deep learning

In [26]:
# Create 1D convolutional model to process sequences
inputs = layers.Input(shape=(1,), dtype=tf.string)
text_vectors = text_vectorizer(inputs) # vectorize text inputs
token_embeddings = token_embed(text_vectors) # create embedding
x = layers.Conv1D(64, kernel_size=5, padding="same", activation="relu")(token_embeddings)
x = layers.GlobalAveragePooling1D()(x)
outputs = layers.Dense(num_classes, activation="softmax")(x)
model_1 = tf.keras.Model(inputs, outputs)

# Compile
model_1.compile(loss="categorical_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

# Fit the model
model_1_history = model_1.fit(train_dataset,
                              steps_per_epoch=int(0.1 * len(train_dataset)), # only fit on 10% of batches for faster training time
                              epochs=3,
                              validation_data=valid_dataset,
                              validation_steps=int(0.1 * len(valid_dataset))) # only validate on 10% of batches

Epoch 1/3
562/562 [==============================] - 28s 45ms/step - loss: 0.9184 - accuracy: 0.6353 - val_loss: 0.6911 - val_accuracy: 0.7354
Epoch 2/3
562/562 [==============================] - 5s 9ms/step - loss: 0.6627 - accuracy: 0.7534 - val_loss: 0.6349 - val_accuracy: 0.7640
Epoch 3/3
562/562 [==============================] - 5s 9ms/step - loss: 0.6238 - accuracy: 0.7726 - val_loss: 0.6036 - val_accuracy: 0.7816


In [27]:

# Fit the model with callbacks
model_1_history = model_1.fit(train_dataset,
        steps_per_epoch=int(0.1 * len(train_dataset)),
        epochs=10,
        validation_data=valid_dataset,
        validation_steps=int(0.1 * len(valid_dataset)),
)


Epoch 1/10
562/562 [==============================] - 4s 6ms/step - loss: 0.5243 - accuracy: 0.8157 - val_loss: 0.5914 - val_accuracy: 0.7945
Epoch 2/10
562/562 [==============================] - 4s 7ms/step - loss: 0.4605 - accuracy: 0.8392 - val_loss: 0.5941 - val_accuracy: 0.7859
Epoch 3/10
562/562 [==============================] - 5s 9ms/step - loss: 0.4461 - accuracy: 0.8432 - val_loss: 0.6037 - val_accuracy: 0.7799
Epoch 4/10
562/562 [==============================] - 5s 10ms/step - loss: 0.5867 - accuracy: 0.7902 - val_loss: 0.5652 - val_accuracy: 0.7982
Epoch 5/10
562/562 [==============================] - 8s 14ms/step - loss: 0.5837 - accuracy: 0.7933 - val_loss: 0.5506 - val_accuracy: 0.8025
Epoch 6/10
562/562 [==============================] - 10s 18ms/step - loss: 0.5717 - accuracy: 0.7925 - val_loss: 0.5480 - val_accuracy: 0.8052
Epoch 7/10
562/562 [==============================] - 7s 12ms/step - loss: 0.5517 - accuracy: 0.8001 - val_loss: 0.5346 - val_accuracy: 0.8125
E

### Validate the data

In [28]:
model_1.evaluate(valid_dataset)

945/945 [==============================] - 3s 3ms/step - loss: 0.5190 - accuracy: 0.8143


[0.518982470035553, 0.8143453001976013]

### Use the test Data

In [38]:
model_1.evaluate(test_dataset)

942/942 [==============================] - 3s 3ms/step - loss: 0.5330 - accuracy: 0.8074


[0.5329902768135071, 0.8074000477790833]

In [29]:
# Make predictions (our model outputs prediction probabilities for each class)
model_1_pred_probs = model_1.predict(valid_dataset)
model_1_pred_probs

945/945 [==============================] - 2s 2ms/step


array([[6.1612225e-01, 9.8464824e-02, 9.7922139e-02, 1.4627838e-01,
        4.1212417e-02],
       [5.0072670e-01, 2.3775791e-01, 1.5387035e-02, 2.1397713e-01,
        3.2151241e-02],
       [1.8660115e-01, 5.4729367e-03, 1.4936671e-03, 8.0639380e-01,
        3.8408478e-05],
       ...,
       [1.1618278e-05, 2.0089322e-04, 2.0683624e-03, 7.9500132e-06,
        9.9771118e-01],
       [1.0456488e-01, 4.9914655e-01, 1.4925465e-01, 5.1436801e-02,
        1.9559708e-01],
       [2.5305411e-02, 9.5988077e-01, 9.5770722e-03, 1.0103915e-03,
        4.2263987e-03]], dtype=float32)

In [30]:
# Convert pred probs to classes
model_1_preds = tf.argmax(model_1_pred_probs, axis=1)

calculate_results(val_labels_encoded , model_1_preds)

{'accuracy': 81.4345293260956,
 'precision': 0.8103982726294084,
 'recall': 0.814345293260956,
 'f1': 0.8111719775418158}

test_pred_classes = [label_encoder.classes_[pred] for pred in model_1_preds]
test_pred_classes

In [39]:
test_pred = model_1.predict(test_dataset)
model_test_pred = tf.argmax(test_pred , axis = 1)

calculate_results(test_labels_encoded , model_test_pred)

942/942 [==============================] - 4s 4ms/step


{'accuracy': 80.74000331840054,
 'precision': 0.8029021502527804,
 'recall': 0.8074000331840053,
 'f1': 0.8040905213617323}

In [31]:
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix


In [32]:
tf.cast(0, tf.int64)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [33]:
cm = confusion_matrix(val_labels_encoded, model_1_preds)
cm

array([[2102,  578,  305,  412,   52],
       [ 301, 3467,  173,   31,  610],
       [  97,   92, 9016,   74,  685],
       [ 617,  235,  185, 1312,   27],
       [  28,  372,  731,    4, 8706]])

In [34]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [37]:
from google.colab import files
model_1.save("Medical_paper_abstract_classification")

files.download("Medical_paper_abstract_classification")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>